api:

  name: HUBF - DOWNLOAD IMAGEM (Deletar API 1.0.126)
  path: /api/v1/hub/imagem-deletar-api-1.0.126
  backendBasepath: "http://brai-srv-dcom-recebiveis-service.cd-antecipacao.svc.cluster.local:8443"

 #Exemplo arquivo de configuração utilizado pelo ambiente de DEV
 
  inboundProfiles:
    # corsConfigFile: cors-default.yaml
    securityProfile: 
      type: apiKey
      fieldName: access-token #nome do campo que contém a API KEY
      takeFrom: query # local de onde a API Key será extraída [query | header]

      # type: invokePolicy
      # policyName: Jwk-InboundPolicy
      # useClientRegistry: false                           # Se nao informar o valor sera false por padrao
      # subjectSelector: "${authentication.subject.id}"   # Se nao informar o valor sera por padrao "${authentication.subject.id}"

  # # outboundProfiles: 
  #   authenticationProfile: "my auth profile"
  #   routeType: "proxy"
  #   requestPolicy: "My Request Policy"
  #   responsePolicy: "My response policy"
  #   faultHandlerPolicy: "My fault handler policy"

  certificate:
    useDefaultBradescoCertificates: false # inclui certifidados root, issuing 3 e issuing 4
    certificateFile: "my custom certificate"

  quotas:
    transactionsPerSecond: 3000 #numero de tps

  tags:
  - name: infra
    values: cloud
  - name: tipo-api
    values: interna
  - name: asset
    values: esteira-deletar-api

  methods:
    - name: "errorHtmlUsingGET" 
      quotas:
        transactionsPerSecond: 3 #numero de tps

      tags:
        - name: tag-method-01
          values: "valor-tag-01"
        - name: tag-method-01-b
          values:
          - valor-b-01
          - valor-b-02

    - name: "errorHtmlUsingGET2" 
      quotas:
        transactionsPerSecond: 600 #numero de tps

      tags:
        - name: tag-method-02
          values: "valor-tag-02"
        - name: tag-method-02-b
          values:
          - valor-b-03
          - valor-b-04-08