openapi: "3.1.0"
info:
  title: "API de Referência 2"
  description: "Esta é uma API de referência que atende aos requisitos especificados."
  version: "1.0.3"
  contact:
    name: "JOAO PEDRO ALEXANDRE VIEIRA"
    email: "joao.p.vieira@bradesco.com.br"
tags:
  - name: "general"
    description: "Operações gerais da API"
  - name: "infra"
    description: "cloud"
  - name: "tipo-api"
    description: "comercial"
  - name: "asset"
    description: "gerenciamento"
servers:
  - url: "/api/v1"
    description: "Servidor principal"
security:
  - OAuth2: ["read", "update"]
paths:
  /items:
    get:
      summary: "Listar todos os itens disponíveis no inventário"
      description: "Obtém uma lista de todos os itens disponíveis com detalhes básicos."
      operationId: "listItems"
      tags: ["general"]
      responses:
        "200":
          description: "Lista de itens retornada com sucesso."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Item"
        "400":
          description: "Requisição inválida."
        "403":
          description: "Acesso negado."
        "429":
          description: "Muitas requisições."
        "422":
          description: "Erro de validação."
        "500":
          description: "Erro interno do servidor."
    post:
      summary: "Adicionar um novo item ao inventário"
      description: "Cria um novo item no inventário fornecendo os detalhes necessários."
      operationId: "createItem"
      tags: ["general"]
      requestBody:
        description: "Dados do novo item a ser criado."
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewItem"
      responses:
        "201":
          description: "Item criado com sucesso."
        "400":
          description: "Dados inválidos fornecidos."
        "403":
          description: "Acesso negado."
        "429":
          description: "Muitas requisições."
        "422":
          description: "Erro de validação."
        "500":
          description: "Erro interno do servidor."
  /items/{itemId}:
    get:
      summary: "Obter informações detalhadas de um item pelo ID"
      description: "Recupera informações completas de um item com base no ID fornecido, incluindo metadados adicionais."
      operationId: "getItem"
      tags: ["general","infra"]
      parameters:
        - name: "itemId"
          in: "path"
          description: "O ID único do item a ser recuperado."
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "Detalhes do item retornados com sucesso."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        "400":
          description: "Requisição inválida."
        "403":
          description: "Acesso negado."
        "429":
          description: "Muitas requisições."
        "422":
          description: "Erro de validação."
        "404":
          description: "Item não encontrado."
        "500":
          description: "Erro interno do servidor."
    delete:
      summary: "Remover um item do inventário pelo ID"
      description: "Exclui um item do inventário com base no ID fornecido, garantindo que ele não seja referenciado em outros registros."
      operationId: "deleteItem"
      tags: []
      parameters:
        - name: "itemId"
          in: "path"
          description: "O ID único do item a ser excluído."
          required: true
          schema:
            type: "string"
      responses:
        "400":
          description: "Requisição inválida."
        "403":
          description: "Acesso negado."
        "429":
          description: "Muitas requisições."
        "422":
          description: "Erro de validação."
        "404":
          description: "Item não encontrado."
        "500":
          description: "Erro interno do servidor."
        "501":
          description: "Erro interno do servidor."
components:
  schemas:
    Item:
      type: "object"
      properties:
        id:
          type: "string"
        name:
          type: "string"
        description:
          type: "string"
      required: ["id", "name"]
